Algoritmo "Algoritmos com repetição"

// Estrutura de repetição com teste no início.
// Imprime 10 algarismos(0 até 9(inclusive)).

Var
// Seção de Declarações das variáveis.
   cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   cont <- -1
   enquanto (cont < 9) faca
      cont <- cont + 1
      Escreval(cont," Este é o while!")
   fimenquanto

Fimalgoritmo